<a href="https://colab.research.google.com/github/MiRur730/Statistics/blob/main/confusion_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
actual=   [1,2,4,3,6,4,3,7,2,6,4,5,6,2,1]
predicted=[2,1,4,3,6,1,3,4,5,6,4,4,6,2,1]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
def comp_confmat(actual, predicted):

    # extract the different classes
    classes = np.unique(actual)

    # initialize the confusion matrix
    confmat = np.zeros((len(classes), len(classes)))

    # loop across the different combinations of actual / predicted classes
    for i in range(len(classes)):
        for j in range(len(classes)):

           # count the number of instances in each combination of actual / predicted classes
           confmat[i, j] = np.sum((actual == classes[i]) & (predicted == classes[j]))

    return confmat


In [ ]:
confusion_matrix =comp_confmat(actual,predicted)
print(confusion_matrix)

[[1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0.]
 [1. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [ ]:
total_sum=0
for i in range(0,len(confusion_matrix)):
  for j in range(0,len(confusion_matrix)):
    total_sum+=confusion_matrix[i][j]
total_sum    

15.0

In [ ]:

def multi(mat,n):
  col_sum=[sum([row[i] for row in mat])for i in range(0,len(mat[0]))]
  row_sum=[sum(mat[i]) for i  in range(len(mat))]
  tp=mat[n][n]
  fp =row_sum[n]-tp
  fn=col_sum[n]-tp
  tn=total_sum-fp-fn-tp
  list_store=[]
  accuracy=(tp + tn)/(tp + tn + fp + fn)
  list_store.append(accuracy)
  precision= tp / (tp + fp)
  list_store.append(precision)
  recall = tp / (tp + fn)
  list_store.append(recall)
  f1_score = (2 * precision * recall) / ( precision + recall )
  list_store.append(f1_score)
  return list_store

In [ ]:
print(f" Accuracy for class 1 is {multi(confusion_matrix,1)[0]}")
print(f" Precision for class 1 is {multi(confusion_matrix,1)[1]}")
print(f" Recall for class 1 is {multi(confusion_matrix,1)[2]}")
print(f" f1_score for class 1 is {multi(confusion_matrix,1)[3]}")

 Accuracy for class 1 is 0.8
 Precision for class 1 is 0.3333333333333333
 Recall for class 1 is 0.5
 f1_score for class 1 is 0.4


In [ ]:

for i in range(len(confusion_matrix)):
  print(f"Accuracy for class {i+1} is {multi(confusion_matrix,i)[0]}")
  print(f"Precision for class {i+1} is {multi(confusion_matrix,i)[1]}")
  print(f"Recall for class {i+1}is {multi(confusion_matrix,i)[2]}")
  print(f"F1_score for class {i+1} is {multi(confusion_matrix,i)[3]}")
  print("")

Accuracy for class 1 is 0.8
Precision for class 1 is 0.5
Recall for class 1is 0.3333333333333333
F1_score for class 1 is 0.4

Accuracy for class 2 is 0.8
Precision for class 2 is 0.3333333333333333
Recall for class 2is 0.5
F1_score for class 2 is 0.4

Accuracy for class 3 is 1.0
Precision for class 3 is 1.0
Recall for class 3is 1.0
F1_score for class 3 is 1.0

Accuracy for class 4 is 0.8
Precision for class 4 is 0.6666666666666666
Recall for class 4is 0.5
F1_score for class 4 is 0.5714285714285715

Accuracy for class 5 is 0.8666666666666667
Precision for class 5 is 0.0
Recall for class 5is 0.0
F1_score for class 5 is nan

Accuracy for class 6 is 1.0
Precision for class 6 is 1.0
Recall for class 6is 1.0
F1_score for class 6 is 1.0

Accuracy for class 7 is 0.9333333333333333
Precision for class 7 is 0.0
Recall for class 7is nan
F1_score for class 7 is nan



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]
